//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Example.SiteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Site ServiceSoap", Namespace="http://clients.mindbodyonline.com/api/0_5", ConfigurationName="SiteService.SiteServiceSoap")]
    public interface SiteServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetSites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetSitesResult GetSites(API_Example.SiteService.GetSitesRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetLocationsResult GetLocations(API_Example.SiteService.GetLocationsRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetActivationCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetActivationCodeResult GetActivationCode(API_Example.SiteService.GetActivationCodeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetPrograms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetProgramsResult GetPrograms(API_Example.SiteService.GetProgramsRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetSessionTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetSessionTypesResult GetSessionTypes(API_Example.SiteService.GetSessionTypesRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetResources", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetResourcesResult GetResources(API_Example.SiteService.GetResourcesRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetRelationships", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetRelationshipsResult GetRelationships(API_Example.SiteService.GetRelationshipsRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/GetResourceSchedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.GetResourceScheduleResult GetResourceSchedule(API_Example.SiteService.GetResourceScheduleRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/ReserveResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        API_Example.SiteService.ReserveResourceResult ReserveResource(API_Example.SiteService.ReserveResourceRequest Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSitesRequest : MBRequest {
        
        private string searchTextField;
        
        private System.Nullable<int> relatedSiteIDField;
        
        private System.Nullable<bool> showOnlyTotalWODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchText {
            get {
                return this.searchTextField;
            }
            set {
                this.searchTextField = value;
                this.RaisePropertyChanged("SearchText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> RelatedSiteID {
            get {
                return this.relatedSiteIDField;
            }
            set {
                this.relatedSiteIDField = value;
                this.RaisePropertyChanged("RelatedSiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> ShowOnlyTotalWOD {
            get {
                return this.showOnlyTotalWODField;
            }
            set {
                this.showOnlyTotalWODField = value;
                this.RaisePropertyChanged("ShowOnlyTotalWOD");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReserveResourceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourceScheduleRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRelationshipsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourcesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSessionTypesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetProgramsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetActivationCodeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetLocationsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSitesRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SourceCredentials sourceCredentialsField;
        
        private UserCredentials userCredentialsField;
        
        private System.Nullable<XMLDetailLevel> xMLDetailField;
        
        private System.Nullable<int> pageSizeField;
        
        private System.Nullable<int> currentPageIndexField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SourceCredentials SourceCredentials {
            get {
                return this.sourceCredentialsField;
            }
            set {
                this.sourceCredentialsField = value;
                this.RaisePropertyChanged("SourceCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UserCredentials UserCredentials {
            get {
                return this.userCredentialsField;
            }
            set {
                this.userCredentialsField = value;
                this.RaisePropertyChanged("UserCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<XMLDetailLevel> XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
                this.RaisePropertyChanged("XMLDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
                this.RaisePropertyChanged("CurrentPageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SourceCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceNameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
                this.RaisePropertyChanged("SourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
                this.RaisePropertyChanged("SiteIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/API/0_4")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Relationship : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string relationshipName1Field;
        
        private string relationshipName2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RelationshipName1 {
            get {
                return this.relationshipName1Field;
            }
            set {
                this.relationshipName1Field = value;
                this.RaisePropertyChanged("RelationshipName1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RelationshipName2 {
            get {
                return this.relationshipName2Field;
            }
            set {
                this.relationshipName2Field = value;
                this.RaisePropertyChanged("RelationshipName2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SessionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Program))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Location))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Site siteField;
        
        private string[] messagesField;
        
        private string executeField;
        
        private string errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Site Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("Site");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Execute {
            get {
                return this.executeField;
            }
            set {
                this.executeField = value;
                this.RaisePropertyChanged("Execute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Site : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string logoURLField;
        
        private string pageColor1Field;
        
        private string pageColor2Field;
        
        private string pageColor3Field;
        
        private string pageColor4Field;
        
        private bool acceptsVisaField;
        
        private bool acceptsVisaFieldSpecified;
        
        private bool acceptsDiscoverField;
        
        private bool acceptsDiscoverFieldSpecified;
        
        private bool acceptsMasterCardField;
        
        private bool acceptsMasterCardFieldSpecified;
        
        private bool acceptsAmericanExpressField;
        
        private bool acceptsAmericanExpressFieldSpecified;
        
        private string contactEmailField;
        
        private System.Nullable<bool> eSAField;
        
        private bool eSAFieldSpecified;
        
        private System.Nullable<bool> totalWODField;
        
        private bool totalWODFieldSpecified;
        
        private System.Nullable<bool> taxInclusivePricesField;
        
        private bool taxInclusivePricesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LogoURL {
            get {
                return this.logoURLField;
            }
            set {
                this.logoURLField = value;
                this.RaisePropertyChanged("LogoURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PageColor1 {
            get {
                return this.pageColor1Field;
            }
            set {
                this.pageColor1Field = value;
                this.RaisePropertyChanged("PageColor1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PageColor2 {
            get {
                return this.pageColor2Field;
            }
            set {
                this.pageColor2Field = value;
                this.RaisePropertyChanged("PageColor2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PageColor3 {
            get {
                return this.pageColor3Field;
            }
            set {
                this.pageColor3Field = value;
                this.RaisePropertyChanged("PageColor3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PageColor4 {
            get {
                return this.pageColor4Field;
            }
            set {
                this.pageColor4Field = value;
                this.RaisePropertyChanged("PageColor4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool AcceptsVisa {
            get {
                return this.acceptsVisaField;
            }
            set {
                this.acceptsVisaField = value;
                this.RaisePropertyChanged("AcceptsVisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsVisaSpecified {
            get {
                return this.acceptsVisaFieldSpecified;
            }
            set {
                this.acceptsVisaFieldSpecified = value;
                this.RaisePropertyChanged("AcceptsVisaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool AcceptsDiscover {
            get {
                return this.acceptsDiscoverField;
            }
            set {
                this.acceptsDiscoverField = value;
                this.RaisePropertyChanged("AcceptsDiscover");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsDiscoverSpecified {
            get {
                return this.acceptsDiscoverFieldSpecified;
            }
            set {
                this.acceptsDiscoverFieldSpecified = value;
                this.RaisePropertyChanged("AcceptsDiscoverSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool AcceptsMasterCard {
            get {
                return this.acceptsMasterCardField;
            }
            set {
                this.acceptsMasterCardField = value;
                this.RaisePropertyChanged("AcceptsMasterCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsMasterCardSpecified {
            get {
                return this.acceptsMasterCardFieldSpecified;
            }
            set {
                this.acceptsMasterCardFieldSpecified = value;
                this.RaisePropertyChanged("AcceptsMasterCardSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool AcceptsAmericanExpress {
            get {
                return this.acceptsAmericanExpressField;
            }
            set {
                this.acceptsAmericanExpressField = value;
                this.RaisePropertyChanged("AcceptsAmericanExpress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsAmericanExpressSpecified {
            get {
                return this.acceptsAmericanExpressFieldSpecified;
            }
            set {
                this.acceptsAmericanExpressFieldSpecified = value;
                this.RaisePropertyChanged("AcceptsAmericanExpressSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ContactEmail {
            get {
                return this.contactEmailField;
            }
            set {
                this.contactEmailField = value;
                this.RaisePropertyChanged("ContactEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> ESA {
            get {
                return this.eSAField;
            }
            set {
                this.eSAField = value;
                this.RaisePropertyChanged("ESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESASpecified {
            get {
                return this.eSAFieldSpecified;
            }
            set {
                this.eSAFieldSpecified = value;
                this.RaisePropertyChanged("ESASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> TotalWOD {
            get {
                return this.totalWODField;
            }
            set {
                this.totalWODField = value;
                this.RaisePropertyChanged("TotalWOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalWODSpecified {
            get {
                return this.totalWODFieldSpecified;
            }
            set {
                this.totalWODFieldSpecified = value;
                this.RaisePropertyChanged("TotalWODSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> TaxInclusivePrices {
            get {
                return this.taxInclusivePricesField;
            }
            set {
                this.taxInclusivePricesField = value;
                this.RaisePropertyChanged("TaxInclusivePrices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxInclusivePricesSpecified {
            get {
                return this.taxInclusivePricesFieldSpecified;
            }
            set {
                this.taxInclusivePricesFieldSpecified = value;
                this.RaisePropertyChanged("TaxInclusivePricesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Resource : MBObject {
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("ActionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum ActionCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Added,
        
        /// <remarks/>
        Updated,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Removed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SessionType : MBObject {
        
        private System.Nullable<int> defaultTimeLengthField;
        
        private System.Nullable<int> programIDField;
        
        private System.Nullable<int> numDeductedField;
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> DefaultTimeLength {
            get {
                return this.defaultTimeLengthField;
            }
            set {
                this.defaultTimeLengthField = value;
                this.RaisePropertyChanged("DefaultTimeLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ProgramID {
            get {
                return this.programIDField;
            }
            set {
                this.programIDField = value;
                this.RaisePropertyChanged("ProgramID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> NumDeducted {
            get {
                return this.numDeductedField;
            }
            set {
                this.numDeductedField = value;
                this.RaisePropertyChanged("NumDeducted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("ActionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Program : MBObject {
        
        private int idField;
        
        private string nameField;
        
        private System.Nullable<ScheduleType> scheduleTypeField;
        
        private System.Nullable<int> cancelOffsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<ScheduleType> ScheduleType {
            get {
                return this.scheduleTypeField;
            }
            set {
                this.scheduleTypeField = value;
                this.RaisePropertyChanged("ScheduleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> CancelOffset {
            get {
                return this.cancelOffsetField;
            }
            set {
                this.cancelOffsetField = value;
                this.RaisePropertyChanged("CancelOffset");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum ScheduleType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        DropIn,
        
        /// <remarks/>
        Enrollment,
        
        /// <remarks/>
        Appointment,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Media,
        
        /// <remarks/>
        Arrival,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Location : MBObject {
        
        private System.Nullable<int> businessIDField;
        
        private bool businessIDFieldSpecified;
        
        private int siteIDField;
        
        private bool siteIDFieldSpecified;
        
        private string businessDescriptionField;
        
        private string[] additionalImageURLsField;
        
        private System.Nullable<int> facilitySquareFeetField;
        
        private bool facilitySquareFeetFieldSpecified;
        
        private System.Nullable<int> treatmentRoomsField;
        
        private bool treatmentRoomsFieldSpecified;
        
        private bool proSpaFinderSiteField;
        
        private bool proSpaFinderSiteFieldSpecified;
        
        private bool hasClassesField;
        
        private bool hasClassesFieldSpecified;
        
        private string phoneExtensionField;
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string addressField;
        
        private string address2Field;
        
        private System.Nullable<float> tax1Field;
        
        private bool tax1FieldSpecified;
        
        private System.Nullable<float> tax2Field;
        
        private bool tax2FieldSpecified;
        
        private System.Nullable<float> tax3Field;
        
        private bool tax3FieldSpecified;
        
        private System.Nullable<float> tax4Field;
        
        private bool tax4FieldSpecified;
        
        private System.Nullable<float> tax5Field;
        
        private bool tax5FieldSpecified;
        
        private string phoneField;
        
        private string cityField;
        
        private string stateProvCodeField;
        
        private string postalCodeField;
        
        private System.Nullable<double> latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private System.Nullable<double> longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private System.Nullable<double> distanceInMilesField;
        
        private bool distanceInMilesFieldSpecified;
        
        private string imageURLField;
        
        private string descriptionField;
        
        private System.Nullable<bool> hasSiteField;
        
        private bool hasSiteFieldSpecified;
        
        private System.Nullable<bool> canBookField;
        
        private bool canBookFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> BusinessID {
            get {
                return this.businessIDField;
            }
            set {
                this.businessIDField = value;
                this.RaisePropertyChanged("BusinessID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BusinessIDSpecified {
            get {
                return this.businessIDFieldSpecified;
            }
            set {
                this.businessIDFieldSpecified = value;
                this.RaisePropertyChanged("BusinessIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteIDSpecified {
            get {
                return this.siteIDFieldSpecified;
            }
            set {
                this.siteIDFieldSpecified = value;
                this.RaisePropertyChanged("SiteIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessDescription {
            get {
                return this.businessDescriptionField;
            }
            set {
                this.businessDescriptionField = value;
                this.RaisePropertyChanged("BusinessDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] AdditionalImageURLs {
            get {
                return this.additionalImageURLsField;
            }
            set {
                this.additionalImageURLsField = value;
                this.RaisePropertyChanged("AdditionalImageURLs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> FacilitySquareFeet {
            get {
                return this.facilitySquareFeetField;
            }
            set {
                this.facilitySquareFeetField = value;
                this.RaisePropertyChanged("FacilitySquareFeet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FacilitySquareFeetSpecified {
            get {
                return this.facilitySquareFeetFieldSpecified;
            }
            set {
                this.facilitySquareFeetFieldSpecified = value;
                this.RaisePropertyChanged("FacilitySquareFeetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> TreatmentRooms {
            get {
                return this.treatmentRoomsField;
            }
            set {
                this.treatmentRoomsField = value;
                this.RaisePropertyChanged("TreatmentRooms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TreatmentRoomsSpecified {
            get {
                return this.treatmentRoomsFieldSpecified;
            }
            set {
                this.treatmentRoomsFieldSpecified = value;
                this.RaisePropertyChanged("TreatmentRoomsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool ProSpaFinderSite {
            get {
                return this.proSpaFinderSiteField;
            }
            set {
                this.proSpaFinderSiteField = value;
                this.RaisePropertyChanged("ProSpaFinderSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProSpaFinderSiteSpecified {
            get {
                return this.proSpaFinderSiteFieldSpecified;
            }
            set {
                this.proSpaFinderSiteFieldSpecified = value;
                this.RaisePropertyChanged("ProSpaFinderSiteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool HasClasses {
            get {
                return this.hasClassesField;
            }
            set {
                this.hasClassesField = value;
                this.RaisePropertyChanged("HasClasses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasClassesSpecified {
            get {
                return this.hasClassesFieldSpecified;
            }
            set {
                this.hasClassesFieldSpecified = value;
                this.RaisePropertyChanged("HasClassesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PhoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
                this.RaisePropertyChanged("PhoneExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("ActionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<float> Tax1 {
            get {
                return this.tax1Field;
            }
            set {
                this.tax1Field = value;
                this.RaisePropertyChanged("Tax1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax1Specified {
            get {
                return this.tax1FieldSpecified;
            }
            set {
                this.tax1FieldSpecified = value;
                this.RaisePropertyChanged("Tax1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<float> Tax2 {
            get {
                return this.tax2Field;
            }
            set {
                this.tax2Field = value;
                this.RaisePropertyChanged("Tax2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax2Specified {
            get {
                return this.tax2FieldSpecified;
            }
            set {
                this.tax2FieldSpecified = value;
                this.RaisePropertyChanged("Tax2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<float> Tax3 {
            get {
                return this.tax3Field;
            }
            set {
                this.tax3Field = value;
                this.RaisePropertyChanged("Tax3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax3Specified {
            get {
                return this.tax3FieldSpecified;
            }
            set {
                this.tax3FieldSpecified = value;
                this.RaisePropertyChanged("Tax3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<float> Tax4 {
            get {
                return this.tax4Field;
            }
            set {
                this.tax4Field = value;
                this.RaisePropertyChanged("Tax4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax4Specified {
            get {
                return this.tax4FieldSpecified;
            }
            set {
                this.tax4FieldSpecified = value;
                this.RaisePropertyChanged("Tax4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<float> Tax5 {
            get {
                return this.tax5Field;
            }
            set {
                this.tax5Field = value;
                this.RaisePropertyChanged("Tax5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax5Specified {
            get {
                return this.tax5FieldSpecified;
            }
            set {
                this.tax5FieldSpecified = value;
                this.RaisePropertyChanged("Tax5Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string StateProvCode {
            get {
                return this.stateProvCodeField;
            }
            set {
                this.stateProvCodeField = value;
                this.RaisePropertyChanged("StateProvCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<double> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("LatitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<double> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("LongitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<double> DistanceInMiles {
            get {
                return this.distanceInMilesField;
            }
            set {
                this.distanceInMilesField = value;
                this.RaisePropertyChanged("DistanceInMiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceInMilesSpecified {
            get {
                return this.distanceInMilesFieldSpecified;
            }
            set {
                this.distanceInMilesFieldSpecified = value;
                this.RaisePropertyChanged("DistanceInMilesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ImageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
                this.RaisePropertyChanged("ImageURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<bool> HasSite {
            get {
                return this.hasSiteField;
            }
            set {
                this.hasSiteField = value;
                this.RaisePropertyChanged("HasSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasSiteSpecified {
            get {
                return this.hasSiteFieldSpecified;
            }
            set {
                this.hasSiteFieldSpecified = value;
                this.RaisePropertyChanged("HasSiteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<bool> CanBook {
            get {
                return this.canBookField;
            }
            set {
                this.canBookField = value;
                this.RaisePropertyChanged("CanBook");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanBookSpecified {
            get {
                return this.canBookFieldSpecified;
            }
            set {
                this.canBookFieldSpecified = value;
                this.RaisePropertyChanged("CanBookSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReserveResourceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourceScheduleResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRelationshipsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourcesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSessionTypesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetProgramsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetActivationCodeResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetLocationsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSitesResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusCode statusField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private XMLDetailLevel xMLDetailField;
        
        private int resultCountField;
        
        private int currentPageIndexField;
        
        private int totalPageCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public XMLDetailLevel XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
                this.RaisePropertyChanged("XMLDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
                this.RaisePropertyChanged("ResultCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
                this.RaisePropertyChanged("CurrentPageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TotalPageCount {
            get {
                return this.totalPageCountField;
            }
            set {
                this.totalPageCountField = value;
                this.RaisePropertyChanged("TotalPageCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        InternalException,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        FailedAction,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum XMLDetailLevel {
        
        /// <remarks/>
        Bare,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class ReserveResourceResult : MBResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourceScheduleResult : MBResult {
        
        private Row[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Row[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetRelationshipsResult : MBResult {
        
        private Relationship[] relationshipsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Relationship[] Relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
                this.RaisePropertyChanged("Relationships");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourcesResult : MBResult {
        
        private Resource[] resourcesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Resource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
                this.RaisePropertyChanged("Resources");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSessionTypesResult : MBResult {
        
        private SessionType[] sessionTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SessionType[] SessionTypes {
            get {
                return this.sessionTypesField;
            }
            set {
                this.sessionTypesField = value;
                this.RaisePropertyChanged("SessionTypes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetProgramsResult : MBResult {
        
        private Program[] programsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Program[] Programs {
            get {
                return this.programsField;
            }
            set {
                this.programsField = value;
                this.RaisePropertyChanged("Programs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetActivationCodeResult : MBResult {
        
        private string activationCodeField;
        
        private string activationLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("ActivationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ActivationLink {
            get {
                return this.activationLinkField;
            }
            set {
                this.activationLinkField = value;
                this.RaisePropertyChanged("ActivationLink");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetLocationsResult : MBResult {
        
        private Location[] locationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Location[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
                this.RaisePropertyChanged("Locations");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSitesResult : MBResult {
        
        private Site[] sitesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Site[] Sites {
            get {
                return this.sitesField;
            }
            set {
                this.sitesField = value;
                this.RaisePropertyChanged("Sites");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
                this.RaisePropertyChanged("SiteIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class ReserveResourceRequest : MBRequest {
        
        private int resourceIDField;
        
        private int clientIDField;
        
        private int staffIDField;
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime endDateTimeField;
        
        private int locationIDField;
        
        private int programIDField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
                this.RaisePropertyChanged("ResourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StaffID {
            get {
                return this.staffIDField;
            }
            set {
                this.staffIDField = value;
                this.RaisePropertyChanged("StaffID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
                this.RaisePropertyChanged("StartDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
                this.RaisePropertyChanged("EndDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
                this.RaisePropertyChanged("LocationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ProgramID {
            get {
                return this.programIDField;
            }
            set {
                this.programIDField = value;
                this.RaisePropertyChanged("ProgramID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourceScheduleRequest : MBRequest {
        
        private System.Nullable<System.DateTime> dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetRelationshipsRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourcesRequest : MBRequest {
        
        private int[] sessionTypeIDsField;
        
        private int locationIDField;
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime endDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public int[] SessionTypeIDs {
            get {
                return this.sessionTypeIDsField;
            }
            set {
                this.sessionTypeIDsField = value;
                this.RaisePropertyChanged("SessionTypeIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
                this.RaisePropertyChanged("LocationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
                this.RaisePropertyChanged("StartDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
                this.RaisePropertyChanged("EndDateTime");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSessionTypesRequest : MBRequest {
        
        private int[] programIDsField;
        
        private bool onlineOnlyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public int[] ProgramIDs {
            get {
                return this.programIDsField;
            }
            set {
                this.programIDsField = value;
                this.RaisePropertyChanged("ProgramIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool OnlineOnly {
            get {
                return this.onlineOnlyField;
            }
            set {
                this.onlineOnlyField = value;
                this.RaisePropertyChanged("OnlineOnly");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetProgramsRequest : MBRequest {
        
        private ScheduleType scheduleTypeField;
        
        private bool onlineOnlyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScheduleType ScheduleType {
            get {
                return this.scheduleTypeField;
            }
            set {
                this.scheduleTypeField = value;
                this.RaisePropertyChanged("ScheduleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool OnlineOnly {
            get {
                return this.onlineOnlyField;
            }
            set {
                this.onlineOnlyField = value;
                this.RaisePropertyChanged("OnlineOnly");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetActivationCodeRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetLocationsRequest : MBRequest {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteServiceSoapChannel : API_Example.SiteService.SiteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceSoapClient : System.ServiceModel.ClientBase<API_Example.SiteService.SiteServiceSoap>, API_Example.SiteService.SiteServiceSoap {
        
        public SiteServiceSoapClient() {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public API_Example.SiteService.GetSitesResult GetSites(API_Example.SiteService.GetSitesRequest Request) {
            return base.Channel.GetSites(Request);
        }
        
        public API_Example.SiteService.GetLocationsResult GetLocations(API_Example.SiteService.GetLocationsRequest Request) {
            return base.Channel.GetLocations(Request);
        }
        
        public API_Example.SiteService.GetActivationCodeResult GetActivationCode(API_Example.SiteService.GetActivationCodeRequest Request) {
            return base.Channel.GetActivationCode(Request);
        }
        
        public API_Example.SiteService.GetProgramsResult GetPrograms(API_Example.SiteService.GetProgramsRequest Request) {
            return base.Channel.GetPrograms(Request);
        }
        
        public API_Example.SiteService.GetSessionTypesResult GetSessionTypes(API_Example.SiteService.GetSessionTypesRequest Request) {
            return base.Channel.GetSessionTypes(Request);
        }
        
        public API_Example.SiteService.GetResourcesResult GetResources(API_Example.SiteService.GetResourcesRequest Request) {
            return base.Channel.GetResources(Request);
        }
        
        public API_Example.SiteService.GetRelationshipsResult GetRelationships(API_Example.SiteService.GetRelationshipsRequest Request) {
            return base.Channel.GetRelationships(Request);
        }
        
        public API_Example.SiteService.GetResourceScheduleResult GetResourceSchedule(API_Example.SiteService.GetResourceScheduleRequest Request) {
            return base.Channel.GetResourceSchedule(Request);
        }
        
        public API_Example.SiteService.ReserveResourceResult ReserveResource(API_Example.SiteService.ReserveResourceRequest Request) {
            return base.Channel.ReserveResource(Request);
        }
    }
}
